services:
  # Backend Service (Node.js)
  - type: web
    name: ai-code-reviewer-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: GOOGLE_AI_API_KEY
        sync: false  # Set this in Render dashboard

  # Frontend Service (Static Site - Free)
  - type: static_site
    name: ai-code-reviewer-frontend
    buildCommand: cd frontend && npm install && npm run build
    publishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://ai-code-reviewer-backend.onrender.com
